[project]
name = "maximum-flow-by-augmenting-paths-in-almost-quadratic-time"
version = "0.1.0"
description = ""
authors = [
    {name = "albe2669",email = "albert@risenielsen.dk"},
    {name = "Adrian Borup", email = "adrian@borup.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "meson>=1.7.0",
    "numpy>=2.2.3",
]

[dependency-groups]
dev = [
    "basedpyright>=1.27.1",
    "pytest>=8.3.4",
    "ruff>=0.9.6",
]

[tool.pytest.ini_options]
addopts = "-m \"not slow and not maxflow\""

markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "maxflow: marks tests as maxflow (deselect with '-m \"not maxflow\"')",
]

